export const ActionTypes = {
    CREATE_BOOKMARK: "CREATE_BOOKMARK",
    ARCHIVE_BOOKMARK: "ARCHIVE_BOOKMARK",
    RESTORE_ARCHIVE_BOOKMARK: "RESTORE_ARCHIVE_BOOKMARK",
    DELETE_BOOKMARK: "DELETE_BOOKMARK"
  };